language: node_js
node_js:
  - '10'

sudo: false
dist: trusty

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - secure: K5sRZBHXcHoYfpYEul1tcK2hOp9QMV/T8xmfj1q20AKzw/+ovbsp+Pdb+PbKFr5vP4eN0ISAeHU3nseMGD9tW6BI/Jf1wW4r7qvGch9eH5v1fpAn7Xxm4AqxusxNck7j4uuo720J5nqioZPUjY5ynlgF0iuGJKjx3YVP7t8W4HQ=
    - secure: NbSFG5O6U/6gBMG42vNoRY7Vt0TrDCGunM6MAsTENoRSAN5JFJ1Ne5HfSmOV4hyT63rSTUbNT1zBmqHCfUpZFp+ynVTS3Fs6jv6qgZSZm6l3k5SW1ZGFbDUjxCWuX2lg6n6dV2LyLTnnONa/U/OAb4FkceW9MeKVNjPNv/uYdEA=

addons:
  chrome: stable
  code_climate:
    repo_token:
      secure: "Ilc67FyHl9y9v0e86T9+foBEhWapwwLfqH2T+sc9T8LeaXP+yaE6gf8RjvEALnmcYLWmF3/ZlJsAhpMBJV2I9CV48LPT8qUL7B3AM7EBeLk7GA5q0pEBU90eAW04vNWH9rMXRTaQ6t/me9UvpoFHNghC+Y+J8N/l6g4xF1qjiBA="
  
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  
before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --ignore-engines

stages:
  - test
  - name: npm-release
    if: (tag =~ ^v)
  - name: github-releases
    if: (tag =~ ^v)
  - gh-pages release  

stages:
  - test
  - name: npm release
    if: (tag =~ ^v) AND (branch = master)
  - name: gh-pages release
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      before_script:
        - greenkeeper-lockfile-update
      script:
        - yarn test
      after_script:
        - greenkeeper-lockfile-upload
        - codeclimate-test-reporter < coverage/lcov.info
    - stage: npm release
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function npm_dist_tag() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo "next"
          else
            echo "latest"
          fi
        }
      deploy:
        provider: npm
        tag: $(npm_dist_tag)
        email: chuck.carpenter@me.com
        skip_cleanup: true
        api_key:
          secure: sfjX4OM8lWwyFrzTcypyx4W9ohK+72xdse0Fn2g9jm+pu5EH3ySgmgQ0qinxS5HrOvY8M0wDMU9MqSLI07LDCd3IhNvOSn2KIUlxtO50W6n5Ongh6e0g8jJsRE+pmQq5dX+EdtfDHzxW4Xn3A1zCymcAyMFIiHY+sLtNEDmyDuisEbzx6ZaAvdq09TIR8LnReHRz8+KGDsQ4a3UQt9UCtOc2VFX+uNG6xyt1AV8/gVmgiB4Sqwp1gWluM7P6axY7dtdlJiD8LFdUJ+hbkNJAJ7kwwzVqXsejt5x4qNltPC3Z3SfH5nmZQ8kWARLPZkQvdGQfBLz3Ds+GB/bhKc+X4GmPf5C4eM0u1VRdZDwGtyYdqbJcntlAyNrasFTdd8nNSOdwkhUnFMxD1CnaQQggeGtiELzcVXFsGDyIVLmjHEjyF4L6iiVhPko2KptWDq7ixNTLkGpxXEXAS07H/RtTR6zUXiC+bHlaZIy+ng5FHEvvOyF/ffOqrEsSncSlpE3VPSFFSBVM+bfvVLzFf7EDaIeC7GudPY1cURpIL1CIiuMUCEDVakRc1P/xcUGx4bJ7EbzS6UsODQjy1uwJsHICQvHCgmNluxdbBPIXwFVLj2tUN20lM52YvsBdUEtd93Zg61yjaDC2UYQPFCFfZSOGJ1XBOV2qlzKhKc2FZ5CNBAg=
        on:
          branch: master
          tags: true
          repo: shipshapecode/react-shepherd
        after_deploy: |
          if [ "$(npm_dist_tag)" == "latest" ]; then
            npm dist-tag rm shepherd.js next || true
          fi
    - stage: gh-pages release
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
